name: Sonya's DevLog
author: Sonya Kim
url: https://ssonsonya.github.io
baseurl: 
resume_site: https://ssonsonya.github.io
description: 게임 프로그래머 쏘냐의 개발일지
github_username: ssonsonya
github: https://github.com/ssonsonya
plugins: 
  - jekyll-paginate
  - jekyll-archives
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
categories:
  type: jekyll-archives
  path: /categories/
tags:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archives
    tag: archives
  permalinks:
    category: /categories/:title/
    tag: /tags/:title/

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : d7b73a64cd5bc7920119
    clientSecret : f1d2d06baa9d6cf7bfc07f2a4a4c81ef497ab628
    repo : ssonsonya.github.io
    owner : ssonsonya
    admin : ssonsonya
