title: Sonya's DevLog
author: Sonya Kim
url: https://ssonsonya.github.io
baseurl: 
resume_site: https://drive.google.com/file/d/1E4Qa_nOhDn1iaG_l9wi2SyzTuh0Fs-W2/view?usp=drive_link
description: 게임 프로그래머 쏘냐의 개발일지
github_username: ssonsonya
github: https://github.com/ssonsonya

# Permalinks
permalink: /:year-:month-:day-:title

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives

# Paginator
paginate: 6
paginate_path: "/page/:num/"

# Archives
jekyll-archives:
  enabled:
   - categories
   - tags
  layout: archive
  permalinks: 
    category: "/category/:name/"
    tag: "/tag/:name/"

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown

# Gitalk Comments
comments :
  gitalk :
    clientID : d7b73a64cd5bc7920119
    clientSecret : f1d2d06baa9d6cf7bfc07f2a4a4c81ef497ab628
    repo : ssonsonya.github.io
    owner : ssonsonya
    admin : ssonsonya
